"""empty message

Revision ID: bc9156460b7c
Revises: ea73b987ce7d
Create Date: 2022-12-28 18:25:09.673533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9156460b7c'
down_revision = 'ea73b987ce7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
